# Generated by Django 5.0.4 on 2024-05-14 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 14, 15, 46, 24, 56418), null=True, verbose_name='Последний вход'),
        ),
    ]
