# Generated by Django 5.0.4 on 2024-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_payment_payment_url_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Айди ссессии'),
        ),
    ]
