# Generated by Django 5.0.4 on 2024-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_payment_payment_url_alter_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление'),
        ),
    ]
