# Generated by Django 5.0.4 on 2024-05-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_payment_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='last_update',
        ),
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление'),
        ),
    ]
